### PR TITLE
Update 001._two_sum.md

### PR DESCRIPTION
**Pull request by kunal768**
we can solve it easily using list comprehension

### CODE REVIEW

**Comment by Lisanaaa** [comment]
Sorry I can't merge this, your answer is wrong.

**Comment by kunal768** [comment]
Thanks for responding could you please correct me ... this is giving correct response..

**Comment by Lisanaaa** [comment]
Let's say the inputs are as below:
`nums = [6, 7]
target = 12`

your code will return [0, 0], but there is actually no answer, which means we should return []

**Comment by kunal768** [comment]
I meant b = [[nums.index(i),num.index(j)] for i in nums for j in nums if i+j == target] this while writing the answer the 9 in place of the answer was actually for example reference

**Comment by Lisanaaa** [comment]
if you say that, then your answer is no difference with mine. Please see README.md for PR requirements.

**Comment by kunal768** [comment]
Thanks for rectifying .... will try to come up with something better

**Comment by Lisanaaa** [comment]
Cool!

**Pull request closed without merging**
